<?php

declare(strict_types=1);

/**
 * OpenDXP Monitoring.
 *
 * LICENSE
 *
 * This source file is subject to the GNU General Public License version 3 (GPLv3)
 * For the full copyright and license information, please view the LICENSE.md and gpl-3.0.txt
 * files that are distributed with this source code.
 *
 * @copyright  2025 instride AG (https://instride.ch)
 * @license    https://github.com/instride-ch/opendxp-monitoring/blob/main/gpl-3.0.txt GNU General Public License version 3 (GPLv3)
 */

namespace Instride\Bundle\OpenDxpMonitoringBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\NodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    /**
     * @inheritDoc
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('opendxp_monitoring');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode->append($this->buildReportNode());
        $rootNode->append($this->buildChecksNode());

        return $treeBuilder;
    }

    private function buildReportNode(): NodeDefinition
    {
        $treeBuilder = new TreeBuilder('report');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->scalarNode('api_key')
                    ->info('API key for health report endpoint.')
                    ->isRequired()
                ->end()
                ->scalarNode('default_endpoint')
                    ->info('Default health report API endpoint to send data to.')
                    ->isRequired()
                ->end()
                ->scalarNode('instance_environment')
                    ->info('The name of the environment in which the application is running in.')
                    ->cannotBeEmpty()
                    ->defaultValue('PRD')
                    ->example('PRD, STG, DEV')
                ->end()
            ->end();

        return $rootNode;
    }

    private function buildChecksNode(): NodeDefinition
    {
        $treeBuilder = new TreeBuilder('checks');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->addDefaultsIfNotSet()
            ->children()
                ->arrayNode('app_environment')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->scalarNode('environment')
                            ->info('The environment the application is running in.')
                            ->defaultValue('%kernel.environment%')
                            ->cannotBeEmpty()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('disk_usage')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->integerNode('warning_threshold')
                            ->info('The warning threshold for disk usage in percent.')
                            ->defaultValue(80)
                            ->min(0)->max(100)
                        ->end()
                        ->integerNode('critical_threshold')
                            ->info('The critical threshold for disk usage in percent.')
                            ->defaultValue(90)
                            ->min(0)->max(100)
                        ->end()
                        ->scalarNode('path')
                            ->info('The root directory of the hosting.')
                            ->defaultValue('%kernel.project_dir%')
                            ->cannotBeEmpty()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('doctrine_migrations')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('hosting_size')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->integerNode('warning_threshold')
                            ->info('The warning threshold for the hosting size in bytes.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                        ->integerNode('critical_threshold')
                            ->info('The critical threshold for the hosting size in bytes.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                        ->scalarNode('path')
                            ->info('The root directory of the hosting.')
                            ->defaultValue('%kernel.project_dir%')
                            ->cannotBeEmpty()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('database_size')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->integerNode('warning_threshold')
                            ->info('The warning threshold for the database size in bytes.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                        ->integerNode('critical_threshold')
                            ->info('The critical threshold for the database size in bytes.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('database_table_size')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->integerNode('warning_threshold')
                            ->info('The warning threshold for all database tables size in bytes.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                        ->integerNode('critical_threshold')
                            ->info('The critical threshold for all database tables size in bytes.')
                            ->defaultValue(0)
                            ->min(0)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('https_connection')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('mysql_version')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->scalarNode('version')
                            ->info('The expected version.')
                            ->defaultValue('8.4')
                            ->cannotBeEmpty()
                        ->end()
                        ->scalarNode('operator')
                            ->info('One of: <, lt, <=, le, >, gt, >=, ge, ==, =, eq, !=, <>, ne')
                            ->defaultValue('>=')
                            ->cannotBeEmpty()
                            ->validate()
                                ->ifNotInArray(['<', 'lt', '<=', 'le', '>', 'gt', '>=', 'ge', '==', '=', 'eq', '!=', '<>', 'ne'])
                                ->thenInvalid('Unknown comparison operator %s')
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('php_version')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->scalarNode('version')
                            ->info('The expected version.')
                            ->defaultValue('8.4')
                            ->cannotBeEmpty()
                        ->end()
                        ->scalarNode('operator')
                            ->info('One of: <, lt, <=, le, >, gt, >=, ge, ==, =, eq, !=, <>, ne')
                            ->defaultValue('>=')
                            ->cannotBeEmpty()
                            ->validate()
                                ->ifNotInArray(['<', 'lt', '<=', 'le', '>', 'gt', '>=', 'ge', '==', '=', 'eq', '!=', '<>', 'ne'])
                                ->thenInvalid('Unknown comparison operator %s')
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('opendxp_areabricks')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('opendxp_bundles')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('opendxp_element_count')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                        ->integerNode('warning_threshold')
                            ->info('The warning threshold for amount of OpenDXP elements.')
                            ->defaultValue(135_000)
                            ->min(0)
                        ->end()
                        ->integerNode('critical_threshold')
                            ->info('The critical threshold for amount of OpenDXP elements.')
                            ->defaultValue(150_000)
                            ->min(0)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('opendxp_maintenance')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('opendxp_users')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('opendxp_version')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Enables this check globally.')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('skip')
                            ->info('Skips this check globally.')
                            ->defaultValue(false)
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $rootNode;
    }
}
